swagger:
  specs:
    default:
      pathJson: "swagger.json"
      pathYaml: "swagger.yaml"
      overrideSpec: "classpath:header.yml"
      resourcePackages:
        - io.bootique.swagger.openapi3.demo

swaggerui:
    specUrl: swagger.json